{
 "title": "GenAI SRE Operations Dashboard L1",
 "tags": [ "L1" ],
 "time": { "from": "2026-05-31T09:55:13.586Z", "to": "2026-05-31T09:55:26.986Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "aks-aif-mt-nonprod-ad9d,aks-aif-mt-prod-5f94,aks-aif-dr-prod-08-8b5b"
   },
   {
    "name": "namespace",
    "query": "pg-de-cf-genai-platform,pg-de-cf-genai-platform\nhas context menu, tenant-genai-platform-prod,\ttenant-genai-platform-dev, tenant-genai-platform-dr, tenant-genai-platform-prod, tenant-genai-platform-ext-dev, tenant-genai-platform-ext-stg, tenant-genai-platform-ext-prod"
   },
   {
    "name": "release",
    "label": "release",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "SLOs Based on Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLO Availability (5xx,429)",
   "type": "gauge",
   "description": "GenAI platform availability SLO - Target 99.5% for 28day window",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 5xx and 429 status codes as errors\n| is_5xx_error := if(regex(field=status_code, \"(5..|429)\"), then=1, else=0)\n\n// Step 3: Aggregate the total count of requests and the total count of 5xx errors\n| [sum(is_5xx_error, as=error_count), count(as=total_count)]\n\n| slo_metric := if(total_count > 0, then=(((total_count - error_count) / total_count) * 100), else=100)\n\n// Step 5: Display the final SLO metric\n| select(slo_metric)",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Error Budget used (5xx,429)",
   "type": "stat",
   "description": "Error Budget Used (Target SLO - 99.5)\nfor 28 day window",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 5xx status codes as errors\n| is_5xx_error := if(regex(field=status_code, \"(5..|429)\"), then=1, else=0)\n\n// Step 3: Aggregate the total count of requests and the total count of 5xx errors.\n| [sum(is_5xx_error, as=error_count), count(as=total_count)]\n\n| allowed_error_count := total_count * (1 - 0.995)\n\n// Step 5: Calculate the percentage of the error budget that has been used.\n// If no errors are allowed (i.e., no requests), then 0% of the budget has been used.\n| error_budget_used_percent := if(allowed_error_count > 0, then=((error_count / allowed_error_count) * 100), else=0)\n\n// Step 6: Display the final percentage of the error budget that has been used.\n| select(error_budget_used_percent)\n\n\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Burn rate (5xx, 429 Errors)",
   "type": "timeseries",
   "description": "Platform unavailability Burn rate",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 5xx status codes as errors.\n| is_5xx_error := if(regex(field=status_code, \"(5..|429)\"), then=1, else=0)\n\n// Step 3: Create a timechart with a 1-hour span, getting the sum of errors and total count for each bucket.\n| timechart(span=1h, function=[sum(is_5xx_error, as=errors_in_bucket), count(as=total_in_bucket)])\n\n// Step 4: Calculate the burn rate for each 1-hour bucket.\n// Burn Rate = (Actual Error Rate) / (Allowed Error Rate Threshold)\n// Allowed Error Rate for 99.5% SLO is 0.5% or 0.005.\n| burn_rate_1h := if(total_in_bucket > 0, then=((errors_in_bucket / total_in_bucket) / (1 - 0.995)), else=0)\n\n// Step 5: Display the bucket timestamp and the calculated burn rate.\n| select([@timestamp, _bucket, burn_rate_1h])",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    },
    {
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 5xx status codes as errors.\n| is_5xx_error := if(regex(field=status_code, \"(5..|429)\"), then=1, else=0)\n\n// Step 3: Create a timechart with a 1-hour span, getting the sum of errors and total count for each bucket.\n| timechart(span=10h, function=[sum(is_5xx_error, as=errors_in_bucket), count(as=total_in_bucket)])\n\n// Step 4: Calculate the burn rate for each 1-hour bucket.\n// Burn Rate = (Actual Error Rate) / (Allowed Error Rate Threshold)\n// Allowed Error Rate for 99.5% SLO is 0.5% or 0.005.\n| burn_rate_10h := if(total_in_bucket > 0, then=((errors_in_bucket / total_in_bucket) / (1 - 0.995)), else=0)\n\n| @timestamp := _bucket\n// Step 5: Display the bucket timestamp and the calculated burn rate.\n| select([@timestamp, _bucket, burn_rate_10h])",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "SLO Client Errors (4xx)",
   "type": "gauge",
   "description": "Target SLO is 97% for 28day window",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 4xx status codes as errors\n| is_4xx_error := if(regex(field=status_code, \"4(?!29)\\\\d{2}\"), then=1, else=0)\n\n// Step 3: Aggregate the total count of requests and the total count of 4xx errors\n| [sum(is_4xx_error, as=error_count), count(as=total_count)]\n\n| slo_metric := if(total_count > 0, then=(((total_count - error_count) / total_count) * 100), else=100)\n\n// Step 5: Display the final SLO metric\n| select(slo_metric)",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Error Budget used (4xx)",
   "type": "stat",
   "description": "Error Budget Used (Target SLO - 97)\nfor 28 day window",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 5xx status codes as errors\n| is_5xx_error := if(regex(field=status_code, \"4(?!29)\\\\d{2}\"), then=1, else=0)\n\n// Step 3: Aggregate the total count of requests and the total count of 5xx errors.\n| [sum(is_5xx_error, as=error_count), count(as=total_count)]\n\n| allowed_error_count := total_count * (1 - 0.97)\n\n// Step 5: Calculate the percentage of the error budget that has been used.\n// If no errors are allowed (i.e., no requests), then 0% of the budget has been used.\n| error_budget_used_percent := if(allowed_error_count > 0, then=((error_count / allowed_error_count) * 100), else=0)\n\n// Step 6: Display the final percentage of the error budget that has been used.\n| select(error_budget_used_percent)\n\n\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Burn rate (4xx Errors)",
   "type": "timeseries",
   "description": "Users configuration issues spike burn rate",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 4xx status codes as errors.\n| is_4xx_error := if(regex(field=status_code, \"4(?!29)\\\\d{2}\"), then=1, else=0)\n\n// Step 3: Create a timechart with a 1-hour span, getting the sum of errors and total count for each bucket.\n| timechart(span=1h, function=[sum(is_4xx_error, as=errors_in_bucket), count(as=total_in_bucket)])\n\n// Step 4: Calculate the burn rate for each 1-hour bucket.\n// Burn Rate = (Actual Error Rate) / (Allowed Error Rate Threshold)\n// Allowed Error Rate for 97% SLO is 3% or 0.03.\n| burn_rate_1h := if(total_in_bucket > 0, then=((errors_in_bucket / total_in_bucket) / (1 - 0.97)), else=0)\n\n// Step 5: Display the bucket timestamp and the calculated burn rate.\n| select([_bucket, burn_rate_1h])",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    },
    {
     "lsql": "HTTP\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n// Step 2: Flag requests with 5xx status codes as errors.\n| is_5xx_error := if(regex(field=status_code, \"4(?!29)\\\\d{2}\"), then=1, else=0)\n\n// Step 3: Create a timechart with a 1-hour span, getting the sum of errors and total count for each bucket.\n| timechart(span=10h, function=[sum(is_5xx_error, as=errors_in_bucket), count(as=total_in_bucket)])\n\n// Step 4: Calculate the burn rate for each 1-hour bucket.\n// Burn Rate = (Actual Error Rate) / (Allowed Error Rate Threshold)\n// Allowed Error Rate for 97% SLO is 3% or 0.03.\n| burn_rate_10h := if(total_in_bucket > 0, then=((errors_in_bucket / total_in_bucket) / (1 - 0.97)), else=0)\n\n// Step 5: Display the bucket timestamp and the calculated burn rate.\n| select([_bucket, burn_rate_10h])",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "OpenAI/VertexAI Requests Latency Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "SLO Latency(P95) OpenAI Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"openAI\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'openAI':\\\\s*(?<openAI>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB':\\\\s*(?<cosmosDB>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_prompt':\\\\s*(?<cosmosDB_logging_prompt>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_consumption':\\\\s*(?<cosmosDB_logging_consumption>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.logging_consumption':\\\\s*(?<redis_logging_consumption>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies. Non-existent fields are treated as 0.\n| total_component_latency := redis  + openAI + cosmosDB\n\n// Step 4: Calculate the 95th percentile of the total calculated latency.\n| percentile(field=total_component_latency, percentiles=[95], as=latency)\n\n// Step 5: Assign the result to a clearly named field and display it.\n| p95_latency_sec := latency_95\n| select(p95_latency_sec)\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "SLO Platform Latency(P95) OpenAI Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"openAI\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'openAI':\\\\s*(?<openAI>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB':\\\\s*(?<cosmosDB>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_prompt':\\\\s*(?<cosmosDB_logging_prompt>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_consumption':\\\\s*(?<cosmosDB_logging_consumption>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.logging_consumption':\\\\s*(?<redis_logging_consumption>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies. Non-existent fields are treated as 0.\n| total_component_latency := redis + cosmosDB \n\n// Step 4: Calculate the 95th percentile of the total calculated latency.\n| percentile(field=total_component_latency, percentiles=[95], as=latency)\n\n// Step 5: Assign the result to a clearly named field and display it.\n| p95_latency_sec := latency_95\n| select(p95_latency_sec)\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Error Budget Used (Latency OpenAI)",
   "type": "stat",
   "description": "Error budget used (P95 Latency for 99.5% of time)  > 50 seconds",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"openAI\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'openAI':\\\\s*(?<openAI>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB':\\\\s*(?<cosmosDB>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_prompt':\\\\s*(?<cosmosDB_logging_prompt>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_consumption':\\\\s*(?<cosmosDB_logging_consumption>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.logging_consumption':\\\\s*(?<redis_logging_consumption>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies for each request.\n| total_component_latency := redis +  openAI + cosmosDB \n\n// Step 4: Group requests into 5-minute buckets and calculate the P95 latency for each bucket.\n| timechart(span=5m, function=[percentile(field=total_component_latency, percentiles=[95], as=latency)])\n\n// Step 5: For each 5-minute bucket, flag if its P95 latency exceeds the 100-second SLO target.\n| is_slo_failure := if(latency_95 > 50, then=1, else=0)\n\n// Step 6: Aggregate the results to find the total number of intervals and the number of failed intervals.\n| [sum(is_slo_failure, as=failed_intervals), count(as=total_intervals)]\n\n// Step 7: Calculate the actual percentage of time intervals that failed the SLO.\n| percent_of_time_failed := if(total_intervals > 0, then=((failed_intervals / total_intervals) * 100), else=0)\n\n// Step 8: Calculate the error budget used as a percentage of the allowed budget (5% for a 95% SLO).\n| error_budget_used_percent := if(percent_of_time_failed > 0, then=((percent_of_time_failed / 5) * 100), else=0)\n\n// Step 9: Display the final error budget used percentage.\n| select(error_budget_used_percent)\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "SLO Latency(P95) VertexAI Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"'vertexAI':\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia':\\\\s*(?<multimedia>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia\\\\.request':\\\\s*(?<multimedia_request>\\\\d+\\\\.\\\\d+))?(?:.*?'vertexAI':\\\\s*(?<vertexAI>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies. Non-existent fields are treated as 0.\n| total_component_latency := redis  + multimedia + multimedia_request + vertexAI\n\n// Step 4: Calculate the 95th percentile of the total calculated latency.\n| percentile(field=total_component_latency, percentiles=[95], as=latency)\n\n// Step 5: Assign the result to a clearly named field and display it.\n| p95_latency_sec := latency_95\n| select(p95_latency_sec)\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "SLO Platform Latency(P95) VertexAI Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"'vertexAI':\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia':\\\\s*(?<multimedia>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia\\\\.request':\\\\s*(?<multimedia_request>\\\\d+\\\\.\\\\d+))?(?:.*?'vertexAI':\\\\s*(?<vertexAI>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies. Non-existent fields are treated as 0.\n| total_component_latency := redis  + multimedia + multimedia_request\n\n// Step 4: Calculate the 95th percentile of the total calculated latency.\n| percentile(field=total_component_latency, percentiles=[95], as=latency)\n\n// Step 5: Assign the result to a clearly named field and display it.\n| p95_latency_sec := latency_95\n| select(p95_latency_sec)\n\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Error Budget Used (Latency VertexAI)",
   "type": "stat",
   "description": "Error budget used (P95 Latency for 95% of time)  > 150 seconds",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"'vertexAI':\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 2: Use regex to parse and extract individual component latencies.\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia':\\\\s*(?<multimedia>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia\\\\.request':\\\\s*(?<multimedia_request>\\\\d+\\\\.\\\\d+))?(?:.*?'vertexAI':\\\\s*(?<vertexAI>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies for each request.\n| total_component_latency := redis + multimedia + multimedia_request + vertexAI\n\n// Step 4: Group requests into 5-minute buckets and calculate the P95 latency for each bucket.\n| timechart(span=5m, function=[percentile(field=total_component_latency, percentiles=[95], as=latency)])\n\n// Step 5: For each 5-minute bucket, flag if its P95 latency exceeds the 100-second SLO target.\n| is_slo_failure := if(latency_95 > 150, then=1, else=0)\n\n// Step 6: Aggregate the results to find the total number of intervals and the number of failed intervals.\n| [sum(is_slo_failure, as=failed_intervals), count(as=total_intervals)]\n\n// Step 7: Calculate the actual percentage of time intervals that failed the SLO.\n| percent_of_time_failed := if(total_intervals > 0, then=((failed_intervals / total_intervals) * 100), else=0)\n\n// Step 8: Calculate the error budget used as a percentage of the allowed budget (0.05% for a 95% SLO).\n| error_budget_used_percent := if(percent_of_time_failed > 0, then=((percent_of_time_failed / (1-0.95)) * 100), else=0)\n\n// Step 9: Display the final error budget used percentage.\n| select(error_budget_used_percent)\n",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "// Step 1: Filter for logs that represent HTTP requests using a fast free-text search.\n\"HTTP\" AND not livez\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n| kubernetes.pod_labels.release=$release\n\n// Step 2: Create a time series chart that counts the events in 1-second buckets.\n| timechart(span=1s, function=count(as=all_requests_per_second))",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    },
    {
     "lsql": "// Step 1: Filter for logs that represent HTTP requests using a fast free-text search.\n\"HTTP\" AND not livez AND openai\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 2: Create a time series chart that counts the events in 1-second buckets.\n| timechart(span=1s, function=count(as=openai_requests_per_second))",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    },
    {
     "lsql": "// Step 1: Filter for logs that represent HTTP requests using a fast free-text search.\n\"HTTP\" AND not livez AND vertexai\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 2: Create a time series chart that counts the events in 1-second buckets.\n| timechart(span=1s, function=count(as=vertexai_requests_per_second))",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  { "title": "AKS & Azure Component Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Pod Count",
   "type": "table",
   "description": "You need to see min two containers running. One for Frontend second for backend",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(container) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Restart Reasons",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Max Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(azure_cache_redis_usedmemorypercentage_percent_maximum{resourceName=\"genaipl-redis-prd\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cosmos Max Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "azure_dbformysql_flexibleservers_io_consumption_percent_percent_average{resourceName=\"genaipl-redis-prd\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}