{
 "title": "GenAI SRE Operations Dashboard L2",
 "tags": [ "L2" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "aks-aif-mt-nonprod-ad9d,aks-aif-mt-prod-5f94,aks-aif-dr-prod-08-8b5b"
   },
   {
    "name": "namespace",
    "query": "pg-de-cf-genai-platform,pg-de-cf-genai-platform\nhas context menu, tenant-genai-platform-prod,\ttenant-genai-platform-dev, tenant-genai-platform-dr"
   },
   {
    "name": "release",
    "label": "release",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "AKS& Azure Services Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Count (Instant)",
   "type": "table",
   "description": "You need to see min two containers running. One for Frontend second for backend",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(container) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Restart Reasons",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Max Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(azure_cache_redis_usedmemorypercentage_percent_maximum{resourceName=\"genaipl-redis-prd\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cosmos Max Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "azure_dbformysql_flexibleservers_io_consumption_percent_percent_average{resourceName=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Count (History)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(container) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cosmos I/O Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "azure_dbformysql_flexibleservers_io_consumption_percent_percent_average{resourceName=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors and Latency Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "OpenAI Requests by Status Code",
   "type": "table",
   "description": "400 Bad Request: The server cannot process the request because it contains client-side malformed syntax or invalid message framing.\n\n401 Unauthorized: The request was rejected because it lacks valid authentication credentials for the target resource.\n\n429 Too Many Requests: The client is being rate-limited because it has sent too many requests within a given time period.",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP and openai\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n| groupby(status_code)",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "VertexAI Requests by Status Code",
   "type": "table",
   "description": "400 Bad Request: The server cannot process the request because it contains client-side malformed syntax or invalid message framing.\n\n401 Unauthorized: The request was rejected because it lacks valid authentication credentials for the target resource.\n\n429 Too Many Requests: The client is being rate-limited because it has sent too many requests within a given time period.",
   "gridPos": { "h": 13, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP and vertexai\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n| groupby(status_code) |sort(field=_count)",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Other Requests by Status Code",
   "type": "table",
   "description": "400 Bad Request: The server cannot process the request because it contains client-side malformed syntax or invalid message framing.\n\n401 Unauthorized: The request was rejected because it lacks valid authentication credentials for the target resource.\n\n429 Too Many Requests: The client is being rate-limited because it has sent too many requests within a given time period.",
   "gridPos": { "h": 13, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "HTTP AND NOT \"openai\" AND not \"vertexai\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 1: Extract the 3-digit status code from the log message\n| regex(field=message, \"\\\"\\\\s.*?(?P<status_code>\\\\d{3})\")\n\n| groupby(status_code) |sort(field=_count)",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "P95 Latency OpenAI Requests Per Project",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "// Step 1: Filter for logs containing execution statistics\n\"execution statistics:\" AND \"openAI\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n\n// Step 2: Parse the JSON string in the 'message' field to access its properties\n| parseJson(field=message)\n\n// Step 3: Extract the model name from the request_url\n| regex(field=request_url, \"/v1/openai/deployments/(?P<model_name>[^/]+)/\")\n\n// Step 4: Extract individual latency components from the inner message string\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'openAI':\\\\s*(?<openAI>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB':\\\\s*(?<cosmosDB>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_prompt':\\\\s*(?<cosmosDB_logging_prompt>\\\\d+\\\\.\\\\d+))?(?:.*?'cosmosDB\\\\.logging_consumption':\\\\s*(?<cosmosDB_logging_consumption>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.logging_consumption':\\\\s*(?<redis_logging_consumption>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 5: Sum the component latencies. Non-existent fields are treated as 0.\n| total_component_latency := redis + redis_rate_limit + openAI + cosmosDB + cosmosDB_logging_prompt + cosmosDB_logging_consumption + redis_logging_consumption\n\n// Step 6: Group by model name and calculate the 95th percentile of the total latency for each model\n| timechart(span=10m, function=[percentile(field=total_component_latency, percentiles=[50,95, 99], as=latency)])\n\n// Step 7: Sort the results by latency for easier analysis\n//| sort(field=latency_95)\n\n// Step 8: Display the model name and its calculated p95 latency. The field is named latency_95 by the percentile function.\n//| select([model_name, latency_95])",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "P95 Latency VertexAI Requests Per Project",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "\"execution statistics:\" AND \"'vertexAI':\"\n\n| kubernetes.container.name := #kubernetes.container.name\n\n| drop(#kubernetes.container.name) //aks repository restructure - line can be deleted after 2025-06-01 \n\n| kubernetes.container.name=/$container/i\n\n| #kubernetes.namespace=/$namespace/i\n\n| #kubernetes.cluster=/$cluster/i\n| parseJson(message)\n| regex(field=message, \"execution statistics: {(?:.*?'redis':\\\\s*(?<redis>\\\\d+\\\\.\\\\d+))?(?:.*?'redis\\\\.rate_limit':\\\\s*(?<redis_rate_limit>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia':\\\\s*(?<multimedia>\\\\d+\\\\.\\\\d+))?(?:.*?'multimedia\\\\.request':\\\\s*(?<multimedia_request>\\\\d+\\\\.\\\\d+))?(?:.*?'vertexAI':\\\\s*(?<vertexAI>\\\\d+\\\\.\\\\d+))?.*}\")\n\n// Step 3: Sum the component latencies. Non-existent fields are treated as 0.\n| total_component_latency := redis + redis_rate_limit + multimedia + multimedia_request + vertexAI\n\n// Step 5: Group by project name and calculate the 95th percentile of the total latency for each project\n| timechart(span=10m, function=[percentile(field=total_component_latency, percentiles=[50, 95, 99], as=latency)])\n\n//| sort(field=latency_95)\n\n// Step 6: Display the project name and its calculated p95 latency. The field is named latency_95 by the percentile function.\n//| select([request_project_name, latency_95])",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Errors Vs Project Count",
   "type": "netsage-sankey-panel",
   "description": "https://logscale.spyglass.pg.com/k8s-aks-aif-mt-prod-5f94/dashboards/GenAI%20Platform%20Log%20Analysis%20Dashboard?dashboardId=0UHOVTV94ePPBZro2kbIaRwXp2o5d2un",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "kubernetes.container.name := #kubernetes.container.name | drop(#kubernetes.container.name) | //aks repository restructure - line can be deleted after 2025-06-01 \n#kubernetes.cluster = \"$cluster\"\nAND kubernetes.container.name = \"$container\"\nAND #kubernetes.namespace = \"$namespace\"\nAND kubernetes.pod_labels.release = \"$release\"\n// Step 1: Parse the nested JSON in the message field to extract project name and request ID\n|regex(field=message, \"\\\\\\\"request_project_name\\\\\\\":\\\\s*\\\\\\\"(?<request_project_name>[^\\\\\\\"]+)\\\\\\\".*\\\\\\\"request_id\\\\\\\":\\\\s*\\\\\\\"(?<request_id>[^\\\\\\\"]+)\\\\\\\"\")\n\n| parseJson(message)\n\n| in(field=levelname, values=[\"ERROR\"])\n\n| message != \"Unclosed\"\n\n// Step 3: Display the results in a clean table\n| sankey(source=\"levelname\", target=\"request_project_name\")",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  },
  {
   "title": "Errors Vs Module Count",
   "type": "netsage-sankey-panel",
   "description": "https://logscale.spyglass.pg.com/k8s-aks-aif-mt-prod-5f94/dashboards/GenAI%20Platform%20Log%20Analysis%20Dashboard?dashboardId=0UHOVTV94ePPBZro2kbIaRwXp2o5d2un",
   "gridPos": { "h": 20, "w": 12, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatAs": "logs",
     "lsql": "kubernetes.container.name := #kubernetes.container.name | drop(#kubernetes.container.name) | //aks repository restructure - line can be deleted after 2025-06-01 \n#kubernetes.cluster = \"$cluster\"\nAND kubernetes.container.name = \"$container\"\nAND #kubernetes.namespace = \"$namespace\"\nAND kubernetes.pod_labels.release = \"$release\"\n// Step 1: Parse the nested JSON in the message field to extract project name and request ID\n|regex(field=message, \"\\\\\\\"request_project_name\\\\\\\":\\\\s*\\\\\\\"(?<request_project_name>[^\\\\\\\"]+)\\\\\\\".*\\\\\\\"request_id\\\\\\\":\\\\s*\\\\\\\"(?<request_id>[^\\\\\\\"]+)\\\\\\\"\")\n\n| parseJson(message)\n\n| message != \"Unclosed\"\n\n| in(field=levelname, values=[\"ERROR\"])\n// Step 3: Display the results in a clean table\n| sankey(source=\"levelname\", target=\"module\")",
     "repository": "aks-aif-mt",
     "version": "1.7.6"
    }
   ]
  }
 ]
}