{
 "title": "GenAI Pods",
 "tags": [
  "AskPG",
  "DEV",
  "UAT",
  "PROD",
  "L3"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "tenant-genai-platform-dev, tenant-genai-platform-prod"
   },
   { "name": "ipa_api_server", "label": "ipa-api-server", "query": "ipa-api-server" },
   { "name": "ipa_celery_worker", "label": "ipa-celery-worker", "query": "ipa-celery-worker" },
   { "name": "istio_proxy", "label": "istio-proxy", "query": "istio-proxy" }
  ]
 },
 "panels": [
  {
   "title": "Blocked connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grouped Blocked connections",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "formatAs": "logs",
       "lsql": "#kubernetes.cluster = \"aks-aif-mt-prod-5f94\"\nand #kubernetes.namespace = /tenant-genai-platform|tenant-askpg|tenant-chatpg|tenant-insightspg|tenant-imagepg|pg-de-cf-genai-platform/\nand kubernetes.container.name = \"istio-proxy\"\nand message = /\\boutbound\\|(?!.*\\.svc\\.cluster\\.local\\b)|\\bBlackHoleCluster\\b/i\n| parseCsv(message, delimiter=\" \", columns=[start_time, req_details, response_code, response_flags, response_code_details, connection_termination_details, upstream_transport_failure_reason, bytes_received, bytes_sent, duration, resp_envoy_upstream_service_time, req_x_forwarded_for, req_user_agent, req_x_request_id, req_authority, upstream_host, upstream_cluster_raw, upstream_local_address, downstream_local_address, downstream_remote_address, requested_server_name, route_name])\n| response_flags != \"-\" // checks for any unsuccessful connection\n| drop(@rawstring)\n| parseCsv(downstream_local_address, delimiter=\":\", columns=[ip, port])\n| port != \"80\" // filters istio blocked connections to check check revoked certificates (not possible to whitelist on istio)\n| upstream_host_mask := replace(regex=\"^.*[|]\", field=upstream_cluster_raw)\n| requested_server_name := if(requested_server_name == \"-\", then = upstream_host_mask, else = requested_server_name)\n| rename(field=[[#kubernetes.cluster, cluster], [#kubernetes.namespace, namespace], [kubernetes.container.name, container_name], [kubernetes.pod.name, pod_name]])\n| select([@timestamp, cluster, namespace, pod_name, container_name, response_code, response_flags, direction, upstream_host_mask, requested_server_name, ip, port])\n| groupBy([namespace, upstream_host_mask, requested_server_name, response_flags, port, ip])",
       "repository": "aks-aif-mt",
       "version": "1.7.6"
      }
     ]
    },
    {
     "title": "Blocked connections",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "formatAs": "logs",
       "lsql": "#kubernetes.cluster = \"aks-aif-mt-prod-5f94\"\nand #kubernetes.namespace = /tenant-genai-platform|tenant-askpg|tenant-chatpg|tenant-insightspg|tenant-imagepg|pg-de-cf-genai-platform/\nand kubernetes.container.name = \"istio-proxy\"\nand message = /\\boutbound\\|(?!.*\\.svc\\.cluster\\.local\\b)|\\bBlackHoleCluster\\b/i\n| parseCsv(message, delimiter=\" \", columns=[start_time, req_details, response_code, response_flags, response_code_details, connection_termination_details, upstream_transport_failure_reason, bytes_received, bytes_sent, duration, resp_envoy_upstream_service_time, req_x_forwarded_for, req_user_agent, req_x_request_id, req_authority, upstream_host, upstream_cluster_raw, upstream_local_address, downstream_local_address, downstream_remote_address, requested_server_name, route_name])\n| response_flags != \"-\" // checks for any unsuccessful connection\n| drop(@rawstring)\n| parseCsv(downstream_local_address, delimiter=\":\", columns=[ip, port])\n| port != \"80\" // filters istio blocked connections to check check revoked certificates (not possible to whitelist on istio)\n| upstream_host_mask := replace(regex=\"^.*[|]\", field=upstream_cluster_raw)\n| requested_server_name := if(requested_server_name == \"-\", then = upstream_host_mask, else = requested_server_name)\n| rename(field=[[#kubernetes.cluster, cluster], [#kubernetes.namespace, namespace], [kubernetes.container.name, container_name], [kubernetes.pod.name, pod_name]])\n| select([@timestamp, cluster, namespace, pod_name, container_name, response_code, response_flags, direction, upstream_host_mask, requested_server_name, ip, port])",
       "repository": "aks-aif-mt",
       "version": "1.7.6"
      }
     ]
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "ipa-api-server Current List of Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "count by(cluster,node,pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container=\"$ipa_api_server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa-api-server Count now",
   "type": "stat",
   "description": "You need to see min two containers running. One for Frontend second for backend",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(container) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Nodes different than \"aks-genai-\"",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "count by(cluster,node,pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",node!~\".*aks-genai-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa-celery-worker Current List of Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by(cluster,node,pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container=\"$ipa_celery_worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa-api-server Container Resource Limits",
   "type": "timeseries",
   "description": "You need to see min two containers running. One for Frontend second for backend",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(container) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "istio-proxy Current List of Pods",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count by(cluster,node,pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container=\"istio-proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa-api-server Container Count by CPU Usage",
   "type": "timeseries",
   "description": "You need to see min two containers running. One for Frontend second for backend",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(container) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Mean GenAI Pods CPU usage",
   "type": "stat",
   "description": "How many container CPU is used by all available pods.",
   "gridPos": { "h": 22, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$ipa_api_server\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$ipa_api_server\", resource=\"cpu\"})",
     "legendFormat": "ipa-api-server"
    },
    {
     "expr": "sum (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$ipa_celery_worker\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$ipa_celery_worker\", resource=\"cpu\"})",
     "legendFormat": "ipa-celery-worker"
    },
    {
     "expr": "sum (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$istio_proxy\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$istio_proxy\", resource=\"cpu\"})",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "ipa-api-server CPU usage - count CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$ipa_api_server\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$ipa_api_server\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "ipa_celery_worker CPU usage - count CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$ipa_celery_worker\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$ipa_celery_worker\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "istio_proxy CPU usage - count CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"$istio_proxy\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$istio_proxy\", resource=\"cpu\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Mean GenAI Pods Memory usage",
   "type": "stat",
   "description": "How many container CPU is used by all available pods.",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"}) / sum (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_api_server\"})",
     "legendFormat": "ipa-api-server"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"}) / sum (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})",
     "legendFormat": "ipa-celery-worker"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"}) / sum (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$istio_proxy\"})",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "ipa_api_server Memory usage",
   "type": "stat",
   "description": "How many container memory is used by all available pods.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"}) / sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_api_server\"})"
    }
   ]
  },
  {
   "title": "ipa_api_server Memory limits",
   "type": "stat",
   "description": "On the left we have available memory for container and on the right we have memory consumed by one or more active pod ",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_api_server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa_celery_worker Memory usage",
   "type": "stat",
   "description": "On the left we have available memory for container and on the right we have memory consumed by one or more active pod ",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa_api_server MAX Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"})"
    }
   ]
  },
  {
   "title": "ipa_api_server MAX Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"})"
    }
   ]
  },
  {
   "title": "ipa_api_server AVG Memory usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"})"
    }
   ]
  },
  {
   "title": "ipa_api_server Memory usage",
   "type": "timeseries",
   "description": "How many container memory is used by all available pods.",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_api_server\"}) / sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_api_server\"})"
    }
   ]
  },
  {
   "title": "ipa_celery_worker Memory usage",
   "type": "stat",
   "description": "How many container memory is used by all available pods.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"}) / sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})"
    }
   ]
  },
  {
   "title": "ipa_celery_worker Memory limits",
   "type": "stat",
   "description": "On the left we have available memory for container and on the right we have memory consumed by one or more active pod ",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa_celery_worker Memory usage",
   "type": "stat",
   "description": "On the left we have available memory for container and on the right we have memory consumed by one or more active pod ",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipa_celery_worker MAX Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})"
    }
   ]
  },
  {
   "title": "ipa_celery_worker MAX Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})"
    }
   ]
  },
  {
   "title": "ipa_celery_worker AVG Memory usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})"
    }
   ]
  },
  {
   "title": "ipa_celery_worker Memory usage",
   "type": "timeseries",
   "description": "How many container memory is used by all available pods.",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$ipa_celery_worker\"}) / sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$ipa_celery_worker\"})"
    }
   ]
  },
  {
   "title": "istio_proxy Memory usage",
   "type": "stat",
   "description": "How many container memory is used by all available pods.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"}) / sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$istio_proxy\"})"
    }
   ]
  },
  {
   "title": "istio_proxy Memory limits",
   "type": "stat",
   "description": "On the left we have available memory for container and on the right we have memory consumed by one or more active pod ",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$istio_proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "istio-proxy Memory usage",
   "type": "stat",
   "description": "On the left we have available memory for container and on the right we have memory consumed by one or more active pod ",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "istio-proxy MAX Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"})"
    }
   ]
  },
  {
   "title": "istio_proxy MAX Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"})"
    }
   ]
  },
  {
   "title": "Security AVG Memory usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"})"
    }
   ]
  },
  {
   "title": "istio-proxy Memory usage",
   "type": "timeseries",
   "description": "How many container memory is used by all available pods.",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$istio_proxy\"}) / sum by(pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$istio_proxy\"})"
    }
   ]
  }
 ]
}