{
 "title": "OpenAI Requests",
 "description": "Availability percentage with the following calculation: (Total Calls - Server Errors)/Total Calls. Server Errors include any HTTP responses >=500. Do not use for Azure OpenAI service.",
 "tags": [
  "GenAI",
  "OpenAI",
  "L3"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Availability Min", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SuccessRate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(azure_cognitiveservices_accounts_successrate_percent_minimum{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (sum_over_time(azure_cognitiveservices_accounts_azureopenairequests_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "{{dimension_Region}}"
    }
   ]
  },
  {
   "title": "SuccessRate by Region",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min by(dimension_region) (azure_cognitiveservices_accounts_successrate_percent_minimum{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Server Errors in Region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(sum by(dimension_Region) (sum_over_time(azure_cognitiveservices_accounts_servererrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range])))",
     "legendFormat": "Total Error"
    }
   ]
  },
  {
   "title": "Total Server Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (sum_over_time(azure_cognitiveservices_accounts_servererrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "{{dimension_Region}}"
    }
   ]
  },
  {
   "title": "Server Errors by Region",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(dimension_region) (sum_over_time(azure_cognitiveservices_accounts_servererrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Errors by RatelimitKey",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dimension_RatelimitKey) (sum_over_time(azure_cognitiveservices_accounts_servererrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Errors By Region",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(dimension_region) (sum_over_time(azure_cognitiveservices_accounts_servererrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Max Client Errors by Region",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(azure_cognitiveservices_accounts_clienterrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Errors by ApiName",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dimension_apiname) (sum_over_time(azure_cognitiveservices_accounts_clienterrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Errors by Region",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dimension_region) (sum_over_time(azure_cognitiveservices_accounts_clienterrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Errors by Operation",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dimension_operationName) (sum_over_time(azure_cognitiveservices_accounts_clienterrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Client Errors by RatelimitKey",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dimension_RatelimitKey) (sum_over_time(azure_cognitiveservices_accounts_clienterrors_count_total{resourceGroup=\"az-rg-aip-mlwgenaiplatform\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}